name: firebase_todo_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+3
  firebase_core: ^0.5.2+1
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.3+1
  firebase_storage: ^5.2.0
  image_picker: ^0.6.7+17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
