// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC593zCLrbPw3fv_UHwWiTWaLAQTSbYXec',
    appId: '1:99941983520:web:384746a7fda7a83607a345',
    messagingSenderId: '99941983520',
    projectId: 'tabikan-9ea00',
    authDomain: 'tabikan-9ea00.firebaseapp.com',
    storageBucket: 'tabikan-9ea00.appspot.com',
    measurementId: 'G-60SNC7XXKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp6b4b-z1mJWUULqkdUGD_p_FWMlOJIV8',
    appId: '1:99941983520:android:5bc8b97c2ba39a4407a345',
    messagingSenderId: '99941983520',
    projectId: 'tabikan-9ea00',
    storageBucket: 'tabikan-9ea00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF9L9c5OWsNmcM-MONhr2BvA-7xh0Y37Q',
    appId: '1:99941983520:ios:c4841306c3f3d6d707a345',
    messagingSenderId: '99941983520',
    projectId: 'tabikan-9ea00',
    storageBucket: 'tabikan-9ea00.appspot.com',
    iosClientId: '99941983520-d47tkofo35rffugctbc2t6aoibo1kd20.apps.googleusercontent.com',
    iosBundleId: 'com.warikanFirebaseApp',
  );
}
